# generated by datamodel-codegen:
#   filename:  closePosition.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class ClosePositionParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
