# generated by datamodel-codegen:
#   filename:  decreasePosition.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class DecreasePositionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    leverage_multiple: str
    vUSD_amount: str
